- ebl/auth0.py
- ebl/corpus/text_validator.py
- ebl/fragmentarium/update_signs.py
- ebl/fragmentarium/validate_fragments.py
- ebl/tests/text/test_atf_parser.py
- ebl/tests/text/test_line.py
- ebl/tests/text/test_parse_word.py
- ebl/text/text.py
- ebl/text/text_parser.py
- ebl/text/token.py
- ebl/text/visitors.py
See: https://trello.com/c/077195Rq
> Fix broken-away next to other enclosure

- docs/ebl-atf.md
Add specification and grammar for all top-level tokens.
> Top-level tokens

- ebl/fragmentarium/application/fragment_matcher.py
- ebl/fragmentarium/application/fragment_repository.py
- ebl/fragmentarium/application/line_to_vec.py
- ebl/fragmentarium/application/line_to_vec_ranking_schema.py
- ebl/fragmentarium/infrastructure/fragment_repository.py
- ebl/tests/fragmentarium/test_fragment_matcher.py
- ebl/tests/fragmentarium/test_fragment_matcher_route.py
- ebl/tests/fragmentarium/test_fragment_repository.py
- ebl/tests/fragmentarium/test_line_to_vec_ranking_schema.py
and some minor refactors, replacing dicts by classes
> extend api endpoint lineToVec with script tag of fragments 

- ebl/corpus/domain/chapter.py
- ebl/tests/corpus/test_chapter.py
itertools.groupby requires that the input is soretd.
> Use pydash to group extant lines

- README.md
add explanation for installing rust
> add explanation for installing rust

- ebl/corpus/web/bootstrap.py
- ebl/corpus/web/texts.py
- ebl/fragmentarium/web/fragment_search.py
- ebl/tests/corpus/test_texts_route.py
- ebl/tests/fragmentarium/test_fragments_search_route.py
> Fix "Revert "cache for fragmentarium and text search""

- docs/ebl-atf.md
- ebl/tests/transliteration/test_parse_introduction.py
- ebl/transliteration/application/note_line_part_schemas.py
- ebl/transliteration/domain/ebl_atf_text_line.lark
- ebl/transliteration/domain/markup.py
- ebl/transliteration/domain/note_line_transformer.py
Allow urls in Markup, syntax: `@url{http://www.example.com/}{Optional display text}`
> Add UrlPart

- ebl/transliteration/domain/markup.py
Reverts ElectronicBabylonianLiterature/ebl-api#321
> Revert "Don't show '@' if reference has no pages"

- ebl/fragmentarium/application/fragment_finder.py
- ebl/fragmentarium/application/fragment_repository.py
- ebl/fragmentarium/infrastructure/fragment_search_aggregations.py
- ebl/fragmentarium/infrastructure/mongo_fragment_repository.py
- ebl/fragmentarium/web/fragments.py
- ebl/tests/fragmentarium/test_fragment_finder.py
add a parameter to explicitly load fragments without their `text.lines`
> Add exclude_lines parameter

- ebl/common/domain/named_enum.py
- ebl/common/domain/period.py
- ebl/common/domain/project.py
- ebl/corpus/application/schemas.py
- ebl/corpus/domain/manuscript.py
- ebl/corpus/domain/text.py
- ebl/fragmentarium/application/fragment_schema.py
- ebl/fragmentarium/domain/fragment.py
- ebl/tests/common/test_period.py
- ebl/tests/common/test_project.py
- ebl/tests/factories/fragment.py
- ebl/tests/fragmentarium/test_dtos.py
Merge  #414 again, without a bug caused by `required=True` on `FragmentSchema.projects`
> Add projects to Fragment 2

- ebl/bibliography/application/reference_schema.py
- ebl/common/query/query_schemas.py
- ebl/corpus/application/id_schemas.py
- ebl/corpus/application/record_schemas.py
- ebl/corpus/application/schemas.py
- ebl/fragmentarium/application/annotations_schema.py
- ebl/fragmentarium/application/fragment_schema.py
- ebl/schemas.py
- ebl/tests/factories/corpus.py
- ebl/tests/fragmentarium/test_dtos.py
- ebl/tests/test_schemas.py
- ebl/transliteration/application/at_line_schemas.py
- ebl/transliteration/application/dollar_line_schemas.py
- ebl/transliteration/application/label_schemas.py
- ebl/transliteration/application/note_line_part_schemas.py
- ebl/transliteration/application/parallel_line_schemas.py
- ebl/transliteration/application/token_schemas.py
- Fix Text.projects field type (`str` -> `ResearchProject`)
- Implement ResearchProject field as class
- Extensive  refactoring
> Fix Text.projects field

- ebl/bibliography/application/bibliography.py
- ebl/bibliography/application/bibliography_repository.py
- ebl/bibliography/infrastructure/bibliography.py
- ebl/common/query/parameter_parser.py
- ebl/tests/bibliography/test_bibliography.py
- ebl/tests/common/test_parameter_parser.py
- ebl/tests/factories/bibliography.py
- ebl/tests/fragmentarium/test_fragments_search_route.py
Bibliography `title-short + volume` search
> Implement `title short + volume` search

- ebl/fragmentarium/application/fragment_schema.py
- ebl/fragmentarium/domain/fragment.py
- ebl/tests/factories/fragment.py
- ebl/tests/fragmentarium/test_fragment.py
corrected "hiprecht" to "hilprecht" in several instances
> corr hilprecht number

- ebl/fragmentarium/application/annotations_schema.py
- ebl/fragmentarium/application/cropped_annotations_service.py
- ebl/fragmentarium/domain/annotation.py
- ebl/fragmentarium/infrastructure/mongo_annotations_repository.py
- ebl/tests/fragmentarium/test_annotations_schema.py
- ebl/tests/fragmentarium/test_cropped_annotations_service.py
* Added provenance String property to AnnotationSchema and Annotations classes
* def find_by_sign now also returns field "provenance"
* Tests are modified to include provenance
> Added provenance property to Annotation class

- ebl/corpus/application/corpus.py
- ebl/corpus/application/text_repository.py
- ebl/corpus/infrastructure/mongo_text_repository.py
- ebl/corpus/web/bootstrap.py
- ebl/corpus/web/chapters.py
- ebl/corpus/web/text_utils.py
A basic public endpoint to fetch the sign information of a single chapter to be used in the standalone n-gram matcher.
> Chapter Sign Endpoint

- .gitpod.Dockerfile
- ebl/corpus/application/corpus.py
- ebl/corpus/application/text_repository.py
- ebl/corpus/infrastructure/mongo_text_repository.py
- ebl/corpus/web/bootstrap.py
- ebl/corpus/web/chapters.py
- ebl/fragmentarium/application/fragment_repository.py
- ebl/fragmentarium/infrastructure/mongo_fragment_repository.py
- ebl/fragmentarium/web/bootstrap.py
- ebl/fragmentarium/web/fragments.py
- ebl/tests/corpus/test_mongo_text_repository.py
- ebl/tests/fragmentarium/test_fragment_repository.py
Endpoints to fetch sign data for all chapters and fragments, for use in n-gram matcher
> Batch Sign Endpoints

- ebl/fragmentarium/infrastructure/fragment_pattern_matcher.py
* Search by parent now available
* Replaced the regex-based search
> Provenance search adaptations

- ebl/fragmentarium/web/fragment_matcher.py
Prevents crawlers from using up all available connections
> Restrict match endpoint

- ebl/fragmentarium/web/provenances.py
- ebl/tests/fragmentarium/test_provenance_route.py
Adjust on_get method to handle compound sites
> Fix provenance resource

- ebl/fragmentarium/web/dtos.py
Authorized scopes are included in Fragment Schema
> Authorized scopes are included in Fragment Schema
